spring.application.name=e-commerce-app

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://dpg-d1bai0re5dus73ednrsg-a:5432/cartdb_8e28?sslmode=require
spring.datasource.username=hari
spring.datasource.password=Ty6RvOb82r7GJcOxCyPtPtljycLn9t6r
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable Spring Security (optional)
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
  org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
