spring.application.name=e-commerce-app
spring.datasource.url=jdbc:postgresql://localhost:5432/Cart
spring.datasource.username=postgres
spring.datasource.password=Hari@2003
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.security.user.name=hari
#spring.security.user.password=1234
# Disable Spring Security auto-configuration
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
  org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
